//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_Carrier", "carrier", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MetricsCorporation.Data.carrier), "primarydata", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MetricsCorporation.Data.primarydata), true)]
[assembly: EdmRelationshipAttribute("MetricsPrimaryDataModel", "fk_ContactInformation_PrimaryData", "primarydata", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MetricsCorporation.Data.primarydata), "contactinformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MetricsCorporation.Data.contactinformation), true)]
[assembly: EdmRelationshipAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_CountyInformation", "countyinformation", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MetricsCorporation.Data.countyinformation), "primarydata", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MetricsCorporation.Data.primarydata), true)]
[assembly: EdmRelationshipAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_EmpSizeCode", "employeesizecode", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MetricsCorporation.Data.employeesizecode), "primarydata", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MetricsCorporation.Data.primarydata), true)]

#endregion

namespace MetricsCorporation.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MetricsPrimaryDataModelEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MetricsPrimaryDataModelEntities object using the connection string found in the 'MetricsPrimaryDataModelEntities' section of the application configuration file.
        /// </summary>
        public MetricsPrimaryDataModelEntities() : base("name=MetricsPrimaryDataModelEntities", "MetricsPrimaryDataModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MetricsPrimaryDataModelEntities object.
        /// </summary>
        public MetricsPrimaryDataModelEntities(string connectionString) : base(connectionString, "MetricsPrimaryDataModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MetricsPrimaryDataModelEntities object.
        /// </summary>
        public MetricsPrimaryDataModelEntities(EntityConnection connection) : base(connection, "MetricsPrimaryDataModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<carrier> carriers
        {
            get
            {
                if ((_carriers == null))
                {
                    _carriers = base.CreateObjectSet<carrier>("carriers");
                }
                return _carriers;
            }
        }
        private ObjectSet<carrier> _carriers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<classcode> classcodes
        {
            get
            {
                if ((_classcodes == null))
                {
                    _classcodes = base.CreateObjectSet<classcode>("classcodes");
                }
                return _classcodes;
            }
        }
        private ObjectSet<classcode> _classcodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<contactinformation> contactinformations
        {
            get
            {
                if ((_contactinformations == null))
                {
                    _contactinformations = base.CreateObjectSet<contactinformation>("contactinformations");
                }
                return _contactinformations;
            }
        }
        private ObjectSet<contactinformation> _contactinformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<countyinformation> countyinformations
        {
            get
            {
                if ((_countyinformations == null))
                {
                    _countyinformations = base.CreateObjectSet<countyinformation>("countyinformations");
                }
                return _countyinformations;
            }
        }
        private ObjectSet<countyinformation> _countyinformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<employeesizecode> employeesizecodes
        {
            get
            {
                if ((_employeesizecodes == null))
                {
                    _employeesizecodes = base.CreateObjectSet<employeesizecode>("employeesizecodes");
                }
                return _employeesizecodes;
            }
        }
        private ObjectSet<employeesizecode> _employeesizecodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<primarydata> primarydatas
        {
            get
            {
                if ((_primarydatas == null))
                {
                    _primarydatas = base.CreateObjectSet<primarydata>("primarydatas");
                }
                return _primarydatas;
            }
        }
        private ObjectSet<primarydata> _primarydatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<siccode> siccodes
        {
            get
            {
                if ((_siccodes == null))
                {
                    _siccodes = base.CreateObjectSet<siccode>("siccodes");
                }
                return _siccodes;
            }
        }
        private ObjectSet<siccode> _siccodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<statecountycode> statecountycodes
        {
            get
            {
                if ((_statecountycodes == null))
                {
                    _statecountycodes = base.CreateObjectSet<statecountycode>("statecountycodes");
                }
                return _statecountycodes;
            }
        }
        private ObjectSet<statecountycode> _statecountycodes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the carriers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocarriers(carrier carrier)
        {
            base.AddObject("carriers", carrier);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the classcodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToclasscodes(classcode classcode)
        {
            base.AddObject("classcodes", classcode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the contactinformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocontactinformations(contactinformation contactinformation)
        {
            base.AddObject("contactinformations", contactinformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the countyinformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocountyinformations(countyinformation countyinformation)
        {
            base.AddObject("countyinformations", countyinformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the employeesizecodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemployeesizecodes(employeesizecode employeesizecode)
        {
            base.AddObject("employeesizecodes", employeesizecode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the primarydatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprimarydatas(primarydata primarydata)
        {
            base.AddObject("primarydatas", primarydata);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the siccodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosiccodes(siccode siccode)
        {
            base.AddObject("siccodes", siccode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the statecountycodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostatecountycodes(statecountycode statecountycode)
        {
            base.AddObject("statecountycodes", statecountycode);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="carrier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class carrier : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new carrier object.
        /// </summary>
        /// <param name="naicNumber">Initial value of the naicNumber property.</param>
        public static carrier Createcarrier(global::System.Decimal naicNumber)
        {
            carrier carrier = new carrier();
            carrier.naicNumber = naicNumber;
            return carrier;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal naicNumber
        {
            get
            {
                return _naicNumber;
            }
            set
            {
                if (_naicNumber != value)
                {
                    OnnaicNumberChanging(value);
                    ReportPropertyChanging("naicNumber");
                    _naicNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("naicNumber");
                    OnnaicNumberChanged();
                }
            }
        }
        private global::System.Decimal _naicNumber;
        partial void OnnaicNumberChanging(global::System.Decimal value);
        partial void OnnaicNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String naicName
        {
            get
            {
                return _naicName;
            }
            set
            {
                OnnaicNameChanging(value);
                ReportPropertyChanging("naicName");
                _naicName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("naicName");
                OnnaicNameChanged();
            }
        }
        private global::System.String _naicName;
        partial void OnnaicNameChanging(global::System.String value);
        partial void OnnaicNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> naicGroupNumber
        {
            get
            {
                return _naicGroupNumber;
            }
            set
            {
                OnnaicGroupNumberChanging(value);
                ReportPropertyChanging("naicGroupNumber");
                _naicGroupNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("naicGroupNumber");
                OnnaicGroupNumberChanged();
            }
        }
        private Nullable<global::System.Decimal> _naicGroupNumber;
        partial void OnnaicGroupNumberChanging(Nullable<global::System.Decimal> value);
        partial void OnnaicGroupNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String naicGroupName
        {
            get
            {
                return _naicGroupName;
            }
            set
            {
                OnnaicGroupNameChanging(value);
                ReportPropertyChanging("naicGroupName");
                _naicGroupName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("naicGroupName");
                OnnaicGroupNameChanged();
            }
        }
        private global::System.String _naicGroupName;
        partial void OnnaicGroupNameChanging(global::System.String value);
        partial void OnnaicGroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_Carrier", "primarydata")]
        public EntityCollection<primarydata> primarydatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<primarydata>("MetricsPrimaryDataModel.fk_PrimaryData_Carrier", "primarydata");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<primarydata>("MetricsPrimaryDataModel.fk_PrimaryData_Carrier", "primarydata", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="classcode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class classcode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new classcode object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static classcode Createclasscode(global::System.Int32 id, global::System.String code, global::System.String description)
        {
            classcode classcode = new classcode();
            classcode.Id = id;
            classcode.Code = code;
            classcode.Description = description;
            return classcode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="contactinformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class contactinformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new contactinformation object.
        /// </summary>
        /// <param name="contactInformationId">Initial value of the contactInformationId property.</param>
        /// <param name="masterUId">Initial value of the masterUId property.</param>
        public static contactinformation Createcontactinformation(global::System.Int64 contactInformationId, global::System.Decimal masterUId)
        {
            contactinformation contactinformation = new contactinformation();
            contactinformation.contactInformationId = contactInformationId;
            contactinformation.masterUId = masterUId;
            return contactinformation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 contactInformationId
        {
            get
            {
                return _contactInformationId;
            }
            set
            {
                if (_contactInformationId != value)
                {
                    OncontactInformationIdChanging(value);
                    ReportPropertyChanging("contactInformationId");
                    _contactInformationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("contactInformationId");
                    OncontactInformationIdChanged();
                }
            }
        }
        private global::System.Int64 _contactInformationId;
        partial void OncontactInformationIdChanging(global::System.Int64 value);
        partial void OncontactInformationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal masterUId
        {
            get
            {
                return _masterUId;
            }
            set
            {
                OnmasterUIdChanging(value);
                ReportPropertyChanging("masterUId");
                _masterUId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("masterUId");
                OnmasterUIdChanged();
            }
        }
        private global::System.Decimal _masterUId;
        partial void OnmasterUIdChanging(global::System.Decimal value);
        partial void OnmasterUIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contactName
        {
            get
            {
                return _contactName;
            }
            set
            {
                OncontactNameChanging(value);
                ReportPropertyChanging("contactName");
                _contactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contactName");
                OncontactNameChanged();
            }
        }
        private global::System.String _contactName;
        partial void OncontactNameChanging(global::System.String value);
        partial void OncontactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phoneNumber
        {
            get
            {
                return _phoneNumber;
            }
            set
            {
                OnphoneNumberChanging(value);
                ReportPropertyChanging("phoneNumber");
                _phoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phoneNumber");
                OnphoneNumberChanged();
            }
        }
        private global::System.String _phoneNumber;
        partial void OnphoneNumberChanging(global::System.String value);
        partial void OnphoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emailAddress
        {
            get
            {
                return _emailAddress;
            }
            set
            {
                OnemailAddressChanging(value);
                ReportPropertyChanging("emailAddress");
                _emailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emailAddress");
                OnemailAddressChanged();
            }
        }
        private global::System.String _emailAddress;
        partial void OnemailAddressChanging(global::System.String value);
        partial void OnemailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_ContactInformation_PrimaryData", "primarydata")]
        public primarydata primarydata
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<primarydata>("MetricsPrimaryDataModel.fk_ContactInformation_PrimaryData", "primarydata").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<primarydata>("MetricsPrimaryDataModel.fk_ContactInformation_PrimaryData", "primarydata").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<primarydata> primarydataReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<primarydata>("MetricsPrimaryDataModel.fk_ContactInformation_PrimaryData", "primarydata");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<primarydata>("MetricsPrimaryDataModel.fk_ContactInformation_PrimaryData", "primarydata", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="countyinformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class countyinformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new countyinformation object.
        /// </summary>
        /// <param name="countyCode">Initial value of the countyCode property.</param>
        public static countyinformation Createcountyinformation(global::System.Int64 countyCode)
        {
            countyinformation countyinformation = new countyinformation();
            countyinformation.countyCode = countyCode;
            return countyinformation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 countyCode
        {
            get
            {
                return _countyCode;
            }
            set
            {
                if (_countyCode != value)
                {
                    OncountyCodeChanging(value);
                    ReportPropertyChanging("countyCode");
                    _countyCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("countyCode");
                    OncountyCodeChanged();
                }
            }
        }
        private global::System.Int64 _countyCode;
        partial void OncountyCodeChanging(global::System.Int64 value);
        partial void OncountyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String countyName
        {
            get
            {
                return _countyName;
            }
            set
            {
                OncountyNameChanging(value);
                ReportPropertyChanging("countyName");
                _countyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("countyName");
                OncountyNameChanged();
            }
        }
        private global::System.String _countyName;
        partial void OncountyNameChanging(global::System.String value);
        partial void OncountyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_CountyInformation", "primarydata")]
        public EntityCollection<primarydata> primarydatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<primarydata>("MetricsPrimaryDataModel.fk_PrimaryData_CountyInformation", "primarydata");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<primarydata>("MetricsPrimaryDataModel.fk_PrimaryData_CountyInformation", "primarydata", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="employeesizecode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employeesizecode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new employeesizecode object.
        /// </summary>
        /// <param name="empSizeCode">Initial value of the empSizeCode property.</param>
        /// <param name="description">Initial value of the description property.</param>
        public static employeesizecode Createemployeesizecode(global::System.Byte empSizeCode, global::System.String description)
        {
            employeesizecode employeesizecode = new employeesizecode();
            employeesizecode.empSizeCode = empSizeCode;
            employeesizecode.description = description;
            return employeesizecode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte empSizeCode
        {
            get
            {
                return _empSizeCode;
            }
            set
            {
                if (_empSizeCode != value)
                {
                    OnempSizeCodeChanging(value);
                    ReportPropertyChanging("empSizeCode");
                    _empSizeCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("empSizeCode");
                    OnempSizeCodeChanged();
                }
            }
        }
        private global::System.Byte _empSizeCode;
        partial void OnempSizeCodeChanging(global::System.Byte value);
        partial void OnempSizeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dnb
        {
            get
            {
                return _dnb;
            }
            set
            {
                OndnbChanging(value);
                ReportPropertyChanging("dnb");
                _dnb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dnb");
                OndnbChanged();
            }
        }
        private global::System.String _dnb;
        partial void OndnbChanging(global::System.String value);
        partial void OndnbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_EmpSizeCode", "primarydata")]
        public EntityCollection<primarydata> primarydatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<primarydata>("MetricsPrimaryDataModel.fk_PrimaryData_EmpSizeCode", "primarydata");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<primarydata>("MetricsPrimaryDataModel.fk_PrimaryData_EmpSizeCode", "primarydata", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="primarydata")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class primarydata : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new primarydata object.
        /// </summary>
        /// <param name="masterUId">Initial value of the masterUId property.</param>
        public static primarydata Createprimarydata(global::System.Decimal masterUId)
        {
            primarydata primarydata = new primarydata();
            primarydata.masterUId = masterUId;
            return primarydata;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal masterUId
        {
            get
            {
                return _masterUId;
            }
            set
            {
                if (_masterUId != value)
                {
                    OnmasterUIdChanging(value);
                    ReportPropertyChanging("masterUId");
                    _masterUId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("masterUId");
                    OnmasterUIdChanged();
                }
            }
        }
        private global::System.Decimal _masterUId;
        partial void OnmasterUIdChanging(global::System.Decimal value);
        partial void OnmasterUIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rmId
        {
            get
            {
                return _rmId;
            }
            set
            {
                OnrmIdChanging(value);
                ReportPropertyChanging("rmId");
                _rmId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rmId");
                OnrmIdChanged();
            }
        }
        private global::System.String _rmId;
        partial void OnrmIdChanging(global::System.String value);
        partial void OnrmIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> recordType
        {
            get
            {
                return _recordType;
            }
            set
            {
                OnrecordTypeChanging(value);
                ReportPropertyChanging("recordType");
                _recordType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recordType");
                OnrecordTypeChanged();
            }
        }
        private Nullable<global::System.Byte> _recordType;
        partial void OnrecordTypeChanging(Nullable<global::System.Byte> value);
        partial void OnrecordTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zipExt
        {
            get
            {
                return _zipExt;
            }
            set
            {
                OnzipExtChanging(value);
                ReportPropertyChanging("zipExt");
                _zipExt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zipExt");
                OnzipExtChanged();
            }
        }
        private global::System.String _zipExt;
        partial void OnzipExtChanging(global::System.String value);
        partial void OnzipExtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> lat
        {
            get
            {
                return _lat;
            }
            set
            {
                OnlatChanging(value);
                ReportPropertyChanging("lat");
                _lat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lat");
                OnlatChanged();
            }
        }
        private Nullable<global::System.Single> _lat;
        partial void OnlatChanging(Nullable<global::System.Single> value);
        partial void OnlatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> @long
        {
            get
            {
                return _long;
            }
            set
            {
                OnlongChanging(value);
                ReportPropertyChanging("long");
                _long = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("long");
                OnlongChanged();
            }
        }
        private Nullable<global::System.Single> _long;
        partial void OnlongChanging(Nullable<global::System.Single> value);
        partial void OnlongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> countyCode
        {
            get
            {
                return _countyCode;
            }
            set
            {
                OncountyCodeChanging(value);
                ReportPropertyChanging("countyCode");
                _countyCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("countyCode");
                OncountyCodeChanged();
            }
        }
        private Nullable<global::System.Int64> _countyCode;
        partial void OncountyCodeChanging(Nullable<global::System.Int64> value);
        partial void OncountyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> empSizeCode
        {
            get
            {
                return _empSizeCode;
            }
            set
            {
                OnempSizeCodeChanging(value);
                ReportPropertyChanging("empSizeCode");
                _empSizeCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("empSizeCode");
                OnempSizeCodeChanged();
            }
        }
        private Nullable<global::System.Byte> _empSizeCode;
        partial void OnempSizeCodeChanging(Nullable<global::System.Byte> value);
        partial void OnempSizeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> peoPayRollId
        {
            get
            {
                return _peoPayRollId;
            }
            set
            {
                OnpeoPayRollIdChanging(value);
                ReportPropertyChanging("peoPayRollId");
                _peoPayRollId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peoPayRollId");
                OnpeoPayRollIdChanged();
            }
        }
        private Nullable<global::System.Int64> _peoPayRollId;
        partial void OnpeoPayRollIdChanging(Nullable<global::System.Int64> value);
        partial void OnpeoPayRollIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sicCode
        {
            get
            {
                return _sicCode;
            }
            set
            {
                OnsicCodeChanging(value);
                ReportPropertyChanging("sicCode");
                _sicCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sicCode");
                OnsicCodeChanged();
            }
        }
        private global::System.String _sicCode;
        partial void OnsicCodeChanging(global::System.String value);
        partial void OnsicCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String classCode
        {
            get
            {
                return _classCode;
            }
            set
            {
                OnclassCodeChanging(value);
                ReportPropertyChanging("classCode");
                _classCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("classCode");
                OnclassCodeChanged();
            }
        }
        private global::System.String _classCode;
        partial void OnclassCodeChanging(global::System.String value);
        partial void OnclassCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String naicsCode
        {
            get
            {
                return _naicsCode;
            }
            set
            {
                OnnaicsCodeChanging(value);
                ReportPropertyChanging("naicsCode");
                _naicsCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("naicsCode");
                OnnaicsCodeChanged();
            }
        }
        private global::System.String _naicsCode;
        partial void OnnaicsCodeChanging(global::System.String value);
        partial void OnnaicsCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statusCode
        {
            get
            {
                return _statusCode;
            }
            set
            {
                OnstatusCodeChanging(value);
                ReportPropertyChanging("statusCode");
                _statusCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statusCode");
                OnstatusCodeChanged();
            }
        }
        private global::System.String _statusCode;
        partial void OnstatusCodeChanging(global::System.String value);
        partial void OnstatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dunsNumber
        {
            get
            {
                return _dunsNumber;
            }
            set
            {
                OndunsNumberChanging(value);
                ReportPropertyChanging("dunsNumber");
                _dunsNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dunsNumber");
                OndunsNumberChanged();
            }
        }
        private global::System.String _dunsNumber;
        partial void OndunsNumberChanging(global::System.String value);
        partial void OndunsNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> dunsConfidenceCode
        {
            get
            {
                return _dunsConfidenceCode;
            }
            set
            {
                OndunsConfidenceCodeChanging(value);
                ReportPropertyChanging("dunsConfidenceCode");
                _dunsConfidenceCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dunsConfidenceCode");
                OndunsConfidenceCodeChanged();
            }
        }
        private Nullable<global::System.Byte> _dunsConfidenceCode;
        partial void OndunsConfidenceCodeChanging(Nullable<global::System.Byte> value);
        partial void OndunsConfidenceCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> dnbClass
        {
            get
            {
                return _dnbClass;
            }
            set
            {
                OndnbClassChanging(value);
                ReportPropertyChanging("dnbClass");
                _dnbClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dnbClass");
                OndnbClassChanged();
            }
        }
        private Nullable<global::System.Byte> _dnbClass;
        partial void OndnbClassChanging(Nullable<global::System.Byte> value);
        partial void OndnbClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String experianID
        {
            get
            {
                return _experianID;
            }
            set
            {
                OnexperianIDChanging(value);
                ReportPropertyChanging("experianID");
                _experianID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("experianID");
                OnexperianIDChanged();
            }
        }
        private global::System.String _experianID;
        partial void OnexperianIDChanging(global::System.String value);
        partial void OnexperianIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> naicNumber
        {
            get
            {
                return _naicNumber;
            }
            set
            {
                OnnaicNumberChanging(value);
                ReportPropertyChanging("naicNumber");
                _naicNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("naicNumber");
                OnnaicNumberChanged();
            }
        }
        private Nullable<global::System.Decimal> _naicNumber;
        partial void OnnaicNumberChanging(Nullable<global::System.Decimal> value);
        partial void OnnaicNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String effectiveDate
        {
            get
            {
                return _effectiveDate;
            }
            set
            {
                OneffectiveDateChanging(value);
                ReportPropertyChanging("effectiveDate");
                _effectiveDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("effectiveDate");
                OneffectiveDateChanged();
            }
        }
        private global::System.String _effectiveDate;
        partial void OneffectiveDateChanging(global::System.String value);
        partial void OneffectiveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String effectiveMonth
        {
            get
            {
                return _effectiveMonth;
            }
            set
            {
                OneffectiveMonthChanging(value);
                ReportPropertyChanging("effectiveMonth");
                _effectiveMonth = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("effectiveMonth");
                OneffectiveMonthChanged();
            }
        }
        private global::System.String _effectiveMonth;
        partial void OneffectiveMonthChanging(global::System.String value);
        partial void OneffectiveMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_Carrier", "carrier")]
        public carrier carrier
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<carrier>("MetricsPrimaryDataModel.fk_PrimaryData_Carrier", "carrier").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<carrier>("MetricsPrimaryDataModel.fk_PrimaryData_Carrier", "carrier").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<carrier> carrierReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<carrier>("MetricsPrimaryDataModel.fk_PrimaryData_Carrier", "carrier");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<carrier>("MetricsPrimaryDataModel.fk_PrimaryData_Carrier", "carrier", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_ContactInformation_PrimaryData", "contactinformation")]
        public EntityCollection<contactinformation> contactinformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<contactinformation>("MetricsPrimaryDataModel.fk_ContactInformation_PrimaryData", "contactinformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<contactinformation>("MetricsPrimaryDataModel.fk_ContactInformation_PrimaryData", "contactinformation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_CountyInformation", "countyinformation")]
        public countyinformation countyinformation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<countyinformation>("MetricsPrimaryDataModel.fk_PrimaryData_CountyInformation", "countyinformation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<countyinformation>("MetricsPrimaryDataModel.fk_PrimaryData_CountyInformation", "countyinformation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<countyinformation> countyinformationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<countyinformation>("MetricsPrimaryDataModel.fk_PrimaryData_CountyInformation", "countyinformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<countyinformation>("MetricsPrimaryDataModel.fk_PrimaryData_CountyInformation", "countyinformation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MetricsPrimaryDataModel", "fk_PrimaryData_EmpSizeCode", "employeesizecode")]
        public employeesizecode employeesizecode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employeesizecode>("MetricsPrimaryDataModel.fk_PrimaryData_EmpSizeCode", "employeesizecode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employeesizecode>("MetricsPrimaryDataModel.fk_PrimaryData_EmpSizeCode", "employeesizecode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<employeesizecode> employeesizecodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employeesizecode>("MetricsPrimaryDataModel.fk_PrimaryData_EmpSizeCode", "employeesizecode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<employeesizecode>("MetricsPrimaryDataModel.fk_PrimaryData_EmpSizeCode", "employeesizecode", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="siccode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class siccode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new siccode object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="division_Letter">Initial value of the Division_Letter property.</param>
        /// <param name="division_Name">Initial value of the Division_Name property.</param>
        /// <param name="sIC_2_Digit_Code">Initial value of the SIC_2_Digit_Code property.</param>
        /// <param name="sIC_2_Digit_Code_Name">Initial value of the SIC_2_Digit_Code_Name property.</param>
        /// <param name="sIC_3_Digit_Code">Initial value of the SIC_3_Digit_Code property.</param>
        /// <param name="sIC_3_Digit_Code_Name">Initial value of the SIC_3_Digit_Code_Name property.</param>
        /// <param name="sIC_4_Digit_Code">Initial value of the SIC_4_Digit_Code property.</param>
        /// <param name="sIC_4_Digit_Code_Name">Initial value of the SIC_4_Digit_Code_Name property.</param>
        public static siccode Createsiccode(global::System.Int32 id, global::System.String division_Letter, global::System.String division_Name, global::System.String sIC_2_Digit_Code, global::System.String sIC_2_Digit_Code_Name, global::System.String sIC_3_Digit_Code, global::System.String sIC_3_Digit_Code_Name, global::System.String sIC_4_Digit_Code, global::System.String sIC_4_Digit_Code_Name)
        {
            siccode siccode = new siccode();
            siccode.Id = id;
            siccode.Division_Letter = division_Letter;
            siccode.Division_Name = division_Name;
            siccode.SIC_2_Digit_Code = sIC_2_Digit_Code;
            siccode.SIC_2_Digit_Code_Name = sIC_2_Digit_Code_Name;
            siccode.SIC_3_Digit_Code = sIC_3_Digit_Code;
            siccode.SIC_3_Digit_Code_Name = sIC_3_Digit_Code_Name;
            siccode.SIC_4_Digit_Code = sIC_4_Digit_Code;
            siccode.SIC_4_Digit_Code_Name = sIC_4_Digit_Code_Name;
            return siccode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Division_Letter
        {
            get
            {
                return _Division_Letter;
            }
            set
            {
                OnDivision_LetterChanging(value);
                ReportPropertyChanging("Division_Letter");
                _Division_Letter = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Division_Letter");
                OnDivision_LetterChanged();
            }
        }
        private global::System.String _Division_Letter;
        partial void OnDivision_LetterChanging(global::System.String value);
        partial void OnDivision_LetterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Division_Name
        {
            get
            {
                return _Division_Name;
            }
            set
            {
                OnDivision_NameChanging(value);
                ReportPropertyChanging("Division_Name");
                _Division_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Division_Name");
                OnDivision_NameChanged();
            }
        }
        private global::System.String _Division_Name;
        partial void OnDivision_NameChanging(global::System.String value);
        partial void OnDivision_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIC_2_Digit_Code
        {
            get
            {
                return _SIC_2_Digit_Code;
            }
            set
            {
                OnSIC_2_Digit_CodeChanging(value);
                ReportPropertyChanging("SIC_2_Digit_Code");
                _SIC_2_Digit_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIC_2_Digit_Code");
                OnSIC_2_Digit_CodeChanged();
            }
        }
        private global::System.String _SIC_2_Digit_Code;
        partial void OnSIC_2_Digit_CodeChanging(global::System.String value);
        partial void OnSIC_2_Digit_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIC_2_Digit_Code_Name
        {
            get
            {
                return _SIC_2_Digit_Code_Name;
            }
            set
            {
                OnSIC_2_Digit_Code_NameChanging(value);
                ReportPropertyChanging("SIC_2_Digit_Code_Name");
                _SIC_2_Digit_Code_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIC_2_Digit_Code_Name");
                OnSIC_2_Digit_Code_NameChanged();
            }
        }
        private global::System.String _SIC_2_Digit_Code_Name;
        partial void OnSIC_2_Digit_Code_NameChanging(global::System.String value);
        partial void OnSIC_2_Digit_Code_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIC_3_Digit_Code
        {
            get
            {
                return _SIC_3_Digit_Code;
            }
            set
            {
                OnSIC_3_Digit_CodeChanging(value);
                ReportPropertyChanging("SIC_3_Digit_Code");
                _SIC_3_Digit_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIC_3_Digit_Code");
                OnSIC_3_Digit_CodeChanged();
            }
        }
        private global::System.String _SIC_3_Digit_Code;
        partial void OnSIC_3_Digit_CodeChanging(global::System.String value);
        partial void OnSIC_3_Digit_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIC_3_Digit_Code_Name
        {
            get
            {
                return _SIC_3_Digit_Code_Name;
            }
            set
            {
                OnSIC_3_Digit_Code_NameChanging(value);
                ReportPropertyChanging("SIC_3_Digit_Code_Name");
                _SIC_3_Digit_Code_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIC_3_Digit_Code_Name");
                OnSIC_3_Digit_Code_NameChanged();
            }
        }
        private global::System.String _SIC_3_Digit_Code_Name;
        partial void OnSIC_3_Digit_Code_NameChanging(global::System.String value);
        partial void OnSIC_3_Digit_Code_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIC_4_Digit_Code
        {
            get
            {
                return _SIC_4_Digit_Code;
            }
            set
            {
                OnSIC_4_Digit_CodeChanging(value);
                ReportPropertyChanging("SIC_4_Digit_Code");
                _SIC_4_Digit_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIC_4_Digit_Code");
                OnSIC_4_Digit_CodeChanged();
            }
        }
        private global::System.String _SIC_4_Digit_Code;
        partial void OnSIC_4_Digit_CodeChanging(global::System.String value);
        partial void OnSIC_4_Digit_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIC_4_Digit_Code_Name
        {
            get
            {
                return _SIC_4_Digit_Code_Name;
            }
            set
            {
                OnSIC_4_Digit_Code_NameChanging(value);
                ReportPropertyChanging("SIC_4_Digit_Code_Name");
                _SIC_4_Digit_Code_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIC_4_Digit_Code_Name");
                OnSIC_4_Digit_Code_NameChanged();
            }
        }
        private global::System.String _SIC_4_Digit_Code_Name;
        partial void OnSIC_4_Digit_Code_NameChanging(global::System.String value);
        partial void OnSIC_4_Digit_Code_NameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MetricsPrimaryDataModel", Name="statecountycode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class statecountycode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new statecountycode object.
        /// </summary>
        /// <param name="county_Number">Initial value of the County_Number property.</param>
        public static statecountycode Createstatecountycode(global::System.Int32 county_Number)
        {
            statecountycode statecountycode = new statecountycode();
            statecountycode.County_Number = county_Number;
            return statecountycode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 County_Number
        {
            get
            {
                return _County_Number;
            }
            set
            {
                if (_County_Number != value)
                {
                    OnCounty_NumberChanging(value);
                    ReportPropertyChanging("County_Number");
                    _County_Number = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("County_Number");
                    OnCounty_NumberChanged();
                }
            }
        }
        private global::System.Int32 _County_Number;
        partial void OnCounty_NumberChanging(global::System.Int32 value);
        partial void OnCounty_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String County_Description
        {
            get
            {
                return _County_Description;
            }
            set
            {
                OnCounty_DescriptionChanging(value);
                ReportPropertyChanging("County_Description");
                _County_Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("County_Description");
                OnCounty_DescriptionChanged();
            }
        }
        private global::System.String _County_Description;
        partial void OnCounty_DescriptionChanging(global::System.String value);
        partial void OnCounty_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State_Prefix
        {
            get
            {
                return _State_Prefix;
            }
            set
            {
                OnState_PrefixChanging(value);
                ReportPropertyChanging("State_Prefix");
                _State_Prefix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State_Prefix");
                OnState_PrefixChanged();
            }
        }
        private global::System.String _State_Prefix;
        partial void OnState_PrefixChanging(global::System.String value);
        partial void OnState_PrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State_Description
        {
            get
            {
                return _State_Description;
            }
            set
            {
                OnState_DescriptionChanging(value);
                ReportPropertyChanging("State_Description");
                _State_Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State_Description");
                OnState_DescriptionChanged();
            }
        }
        private global::System.String _State_Description;
        partial void OnState_DescriptionChanging(global::System.String value);
        partial void OnState_DescriptionChanged();

        #endregion
    
    }

    #endregion
    
}
