//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using MetricsCorporation.Entities;

namespace MetricsCorporation.EFCorePrim
{
    
    public partial class MetricsCorporationPrimComb : DbContext
    {
        public MetricsCorporationPrimComb()
            : base("name=MetricsCorporationPrimComb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comb> combs { get; set; }
        public DbSet<prim> prims { get; set; }
    }
}
