//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using MetricsCorporation.Entities;

namespace MetricsCorporation.EFCore
{
    
    public partial class state_schematicEntities : DbContext
    {
        public state_schematicEntities()
            : base("name=state_schematicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<county> counties { get; set; }
        public DbSet<employeesize> employeesizes { get; set; }
        public DbSet<jigsaw_logins> jigsaw_logins { get; set; }
        public DbSet<loginfo> loginfoes { get; set; }
        public DbSet<masterid> masterids { get; set; }
        public DbSet<searchlog> searchlogs { get; set; }
        public DbSet<siccode> siccodes { get; set; }
        public DbSet<number_of_logins> number_of_logins { get; set; }
        public DbSet<filelist> filelists { get; set; }
        public DbSet<usageinfo> usageinfoes { get; set; }
        public DbSet<user_states> user_states { get; set; }
        public DbSet<exported> exporteds { get; set; }
        public DbSet<exported_company> exported_company { get; set; }
        public DbSet<usercredit> usercredits { get; set; }
    }
}
